spring.application.name=workouts-auth

# Server configuration
server.port=9000

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/workouts_auth
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Actuator configuration
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized

# Logging
logging.level.org.springframework.security=INFO
logging.level.org.springframework.security.oauth2=DEBUG
